name: mrd
channels:
  - conda-forge
  - ismrmrd
  - nodefaults
dependencies:
  - bash-completion=2.11
  - cmake=4.2.2
  - fftw=3.3.10
  - gcc_linux-64=15.2.0
  - gdb=17.1 # local
  - gxx_linux-64=15.2.0
  - h5py=3.15.1
  - hdf5=1.14.6
  - howardhinnant_date=3.0.3
  - imagemagick=7.1.2_8
  - ismrmrd>=1.15.0
  - ipykernel=7.1.0
  - just=1.46.0
  - ninja=1.13.2
  - numpy>=2.2.6
  - nlohmann_json=3.12.0
  - nodejs=24.9.0 # local
  - pillow>=12.1.0
  - python=3.13.7
  - shellcheck=0.10.0
  - xmlschema=2.2.3
  - xtensor=0.27.1
  - pip
  - pip:
    - ismrmrd==1.14.2
    - pypulseq==1.4.2.post1
