name: mrd
channels:
  - conda-forge
  - defaults
dependencies:
  - bash-completion=2.11
  - cmake=3.21.3
  - fmt=8.1.1
  - gcc_linux-64=11.2.0
  - gdb=11.2
  - gxx_linux-64=11.2.0
  - h5py=3.7.0
  - hdf5=1.12.1
  - howardhinnant_date=3.0.1
  - jupyter=1.0.0
  - just=1.5.0
  - ninja=1.11.0
  - matplotlib=3.6.2
  - nlohmann_json=3.10.5
  - python=3.10.5
  - shellcheck=0.8.0
  - valgrind=3.18.1
  - xmlschema=2.2.3
  - xtensor=0.24.2
  - xtensor-fftw=0.2.5
