name: CMake

on:
  push:
    branches: [main]
    tags: ["v*.*.*"]
  pull_request:
    branches: [main]
  workflow_dispatch:
  # release:
  #   types: [created]

# env:
#   BUILD_TYPE: Release
#   REGISTRY: ghcr.io

defaults:
  run:
    # See https://github.com/marketplace/actions/setup-miniconda#important
    shell: bash -el {0}

env:
  # Increase this to manually reset the conda environment cache
  CONDA_CACHE_NUMBER: 0
  YARDL_VERSION: 0.5.0

jobs:
  build:
    runs-on: ubuntu-latest
    # permissions:
    #   contents: read
    #   packages: write

    strategy:
      matrix:
        cppVersion: [17]

    name: Validate C++${{ matrix.cppVersion }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure CPP Build Environment
      uses: ./.github/actions/configure-cpp-build-environment

    - name: Build and Test
      run: just cpp_version=${{ matrix.cppVersion }} validate-with-no-changes

    # - name: Build and test docker images
    #   working-directory: ${{github.workspace}}
    #   shell: bash
    #   run: |
    #     ./docker/build-images.sh
    #     ./docker/test-docker-images.sh

    # - name: Log into registry ${{ env.REGISTRY }}
    #   uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
    #   with:
    #     registry: ${{ env.REGISTRY }}
    #     username: ${{ github.actor }}
    #     password: ${{ secrets.GITHUB_TOKEN }}

    # - name: Push images
    #   if: ${{ github.event_name == 'release' }}
    #   working-directory: ${{github.workspace}}
    #   shell: bash
    #   run: |
    #     ./docker/build-images.sh --tag "${GITHUB_REF##*/}" --push
