name: PyPi

on:
  push:
    branches: [main]
    tags: ["v*.*.*"]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-pypi-package:
    name: Test and Build PyPI Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Python 3.x
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - name: Set up just command runner
        uses: extractions/setup-just@e33e0265a09d6d736e2ee1e0eb685ef1de4669ff

      - name: Build PyPI package
        run: just build-pypi-package

      - name: Store Python package distributions
        uses: actions/upload-artifact@v5
        with:
          name: python-package-distributions
          path: python/dist/
          overwrite: true

  publish:
    name: Publish PyPI Package
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    needs: build-pypi-package
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/mrd-python
    permissions:
      id-token: write   # IMPORTANT: Mandatory for trusted publishing

    steps:
      - name: Download stored package distributions
        uses: actions/download-artifact@v6
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish Package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
