name: Python

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-pypi-package:
    name: Test and Build PyPI Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          # python3 -m pip install -r requirements.txt
          python3 -m pip install build

      # - name: Test
      #   run: python3 -m pytest

      - name: Build PyPI Package
        run: python3 -m build
        working-directory: python/

      - name: Store Python package distributions
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: python/dist/
          overwrite: true

  publish:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build-pypi-package]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/mrd
    permissions:
      id-token: write   # IMPORTANT: Mandatory for trusted publishing

    steps:
      - name: Download stored package distributions
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish Package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        # with:
        #   password: ${{ secrets.PYPI_API_TOKEN }}
