name: PyPi

on:
  push:
    branches: [main]
    tags: ["v*.*.*"]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-pypi-package:
    name: Test and Build PyPI Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Set up just command runner
        uses: extractions/setup-just@dd310ad5a97d8e7b41793f8ef055398d51ad4de6

      - name: Build PyPI package
        run: just build-pypi-package

      - name: Store Python package distributions
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: python/dist/
          overwrite: true

  publish:
    if: false
    # if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    needs: [build-pypi-package]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/mrd
    permissions:
      id-token: write   # IMPORTANT: Mandatory for trusted publishing

    steps:
      - name: Download stored package distributions
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish Package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        # with:
        #   password: ${{ secrets.PYPI_API_TOKEN }}
