name: C++ Conda

on:
  push:
    branches: [main]
    tags: ["v*.*.*"]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-conda-packages:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download MacOSX SDK
        if: startsWith(matrix.os, 'macOS')
        run: |
          curl -o MacOSX10.13.sdk.tar.xz -L https://github.com/phracker/MacOSX-SDKs/releases/download/11.3/MacOSX10.13.sdk.tar.xz && \
          tar xf MacOSX10.13.sdk.tar.xz && \
          sudo mv -v MacOSX10.13.sdk /opt/ && \
          ls /opt/

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          # python-version: 3.11
          auto-activate-base: true
          activate-environment: ""
          miniforge-variant: Miniforge3
          miniforge-version: latest

      - name: Build conda package
        shell: bash -l {0}
        working-directory: cpp/conda
        run: |
          conda install conda-build boa conda-verify anaconda-client
          ./package.sh
          echo "Packages built: $(find build_pkg -name ismrmrd*.tar.bz2)"

      # - name: Push conda package
      #   shell: bash -l {0}
      #   if: ${{ github.event_name == 'release' }}
      #   env:
      #     ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
      #   working-directory: conda
      #   run: |
      #     for p in $(find build_pkg -name ismrmrd*.tar.bz2)
      #     do
      #       ./publish_package.sh -u ismrmrd -t "$ANACONDA_TOKEN" -p "$p"
      #     done
